import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from "./providers";
import FloatingButton from "./component/floatingButton"
import Navbar from "./component/navbars"
import Footer from "./component/footer"


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <meta charSet="utf-8" />
      <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body>
        <Providers>
          <Navbar />
          <FloatingButton />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
